### ISSUE TITLE
Feature Request: Marking pseudo-element classes - for StylableInteligence

### ISSUE THREAD

**Issue by hepiyellow** [wix/stylable#452] opened 2018-11-18 08:38 UTC
StylableInteligence plugin shows all classes as options when I write:
`Comp::`

I would  expect it to show only pseudo-elements.
For that, it would be nice to be able to mark pseudo elements in the stylesheet.

**Comment by idoros** [comment] 2018-11-18 08:41
Other way around, but duplicate of https://github.com/wix/stylable/issues/294

**Closed by idoros** 2018-11-18 08:41 UTC
