### ISSUE TITLE
Allow importing typescript functions/files into stylable

### ISSUE THREAD

**Issue by gilmeir** [wix/stylable#697] opened 2019-07-14 12:50 UTC
Currently it doesn't work, if I strip down ts into js it works.

**Comment by tomrav** [comment] 2020-05-13 09:31
This is not something that we need to enable in Stylable itself, rather, we are missing documentation for how to register/use a typescript loader in our work flows.

Closing as a duplicate of #219

**Closed by tomrav** 2020-05-13 09:31 UTC
Labels: integration, question
