### ISSUE TITLE
Undefined mixin throws exception

### ISSUE THREAD

**Issue by talh78** [wix/stylable#242] opened 2018-01-15 15:14 UTC
Using stylesheet:
```css
.a {
    -st-mixin: Existing(1, 2, 3), Mixins;
}
```

causes an exception to be thrown when an undefined type is accessed [here](https://github.com/wix/stylable/blob/b3995d7b77be591c7ccfac73ce1eb7321e0260f6/src/stylable-value-parsers.ts#L228).

Should fail gracefully, and alert by diagnostics.

**Comment by tomrav** [comment] 2018-06-13 13:37
This appeared to be caused by Stylable thinking this was a CSS mixin and was looking for the value property name.

Should be resolved in #343

**Closed by tomrav** 2018-06-13 13:37 UTC
Labels: bug, core, mixin
