### ISSUE TITLE
Unknown pseudo element -ms-expand

### ISSUE THREAD

**Issue by nullsage** [wix/stylable#851] opened 2019-10-29 13:36 UTC
In our project we have need of a pre-defined microsoft only pseudo element, because of IE 11. This throws a warning in our project.

Example:
```
/* hide the native arrow in IE 11*/
select::-ms-expand {
    display: none;
}
```

All this does is hide the drop down arrow for the select element. Would be nice to have this warning suppressed though.

**Comment by tomrav** [comment] 2019-10-31 10:03
Are you sure you're getting an `unknown pseudo element` warning? I'm not able to reproduce it.

If I use your code example I get `"unscoped element "select" will affect all elements of the same type in the document"`, which is a different warning that notifies you about potential implications of your written selector (you might affect unintended `select` elements as there is no scoping in your selector).

Also, what version of stylable are you using?

**Comment by nullsage** [comment] 2019-11-01 20:11
I do want this to affect everything globally, so that is fine. I am on version:
`"stylable": "5.2.1",
        "stylable-integration": "6.1.2"`

**Comment by tomrav** [comment] 2019-11-03 09:18
A couple of things, first, those are really old versions, we have since moved to scoped packages on npm - `stylable` -> `@stylable/core` and `stylable-integration` -> `@stylable/webpack-plugin`. I strongly recommend that you upgrade to those.

As for the issue at hand - if you want it to affect the entire app, I would recommend creating a theme stylesheet that would have it's `root` class applied to the root of your application, and in that stylesheet perform your cross app customization. By prefixing your selector with that stylesheet's root class, you'll avoid the warning.

```css
/* ./theme.st.css*/
.root select::-ms-expand {
    display: none;
}
```

**Comment by tomrav** [comment] 2019-11-04 15:40
furthermore, we are white-listing all vendor prefixed pseudo elements, so any `*-ms`, `*-moz` or `*-webkit` should not cause an unknown pseudo element warning. 

Closing the issue for now, feel free to re-open if still relevant.

**Closed by tomrav** 2019-11-04 15:40 UTC
Labels: bug, core, diagnostics
