### ISSUE TITLE
Thoughts on namespacing and pseudo-classes

### ISSUE THREAD

**Issue by Scott-MacD** [wix/stylable#316] opened 2018-05-09 01:39 UTC
I didn't really know if this belonged to an existing issue or if there's a more appropriate channel for this as there's not necessarily any action that needs to be taken as you have some existing utilities than can be used to achieve the desired end result (feel free to close). I just wanted to challenge and understand the thinking on the current implementation of data attributes/pseudo-classes and bring some awareness on how this might be used on various rendering libraries that rely on directly parsing template literals into DOM, unlike React/Preact.

Current "Dilemma"
-----------

My specific experience is with [hyperHTML](https://github.com/WebReflection/hyperHTML), but I believe [lit-html](https://github.com/Polymer/lit-html) by the Polymer team functions in a very similar manner, as well as a few other front-end rendering libraries I've stumbled upon. They share the common restriction in that you need to know an attribute name in order to make it part of the template rather than being able to dynamically create attributes on the generated HTML based on given props or otherwise. This causes an issue with creating the template literal that is to be turned into DOM by the parsing function, as you don't know the name of the data-attributes generated by the pseudo elements until you interact with the js runtime to get the namespaced data attribute names.

My thinking is this: **Is it even necessary to namespace data-attributes?** What benefits are to be gained? Isn't `.root:toggled` already namespaced due to `.root` being namespaced itself? I guess there is the risk of `:toggled` being polluted by being passed directly from a parent component to a child component, but I see this as really low risk, in particularly if you stick to conventions on where components are in charge of their own attributes based on either function parameters, props, or state (and in some cases are restricted to do so in how the libraries work anyways). Is there any other big advantage to namespacing data-attributes that I'm not seeing?

Current "Workarounds"
--------

There are three different ways that I can think of to work around the current implmentation, that although none of them feel ideal, all do work.

**The first of which** I started to use and is why I initially filed [this issue](https://github.com/wix/stylable-integration/issues/33), which is to not use the data attributes in the template at all, and instead grab the generated DOM node before returning it on render and then applying the namespaced data-attributes using `Element.setAttribute()`. This has the downside of having to manually manage the DOM in a way that goes against how these libraries are supposed to work, and requires you to manually manage whether a pseudo-class state has changed so you aren't needlessly updating attributes on DOM elements that may have never changed.

**The second option** is to not use pseudo-classes at all, and instead use the data attributes directly. As I'm sure you're already aware, this means to lose all the benefits that come with it such as the type hints, validation, and syntactic simplicity.

**The third option**, which is what I'm using currently, is to use [mapped states](https://stylable.io/docs/references/pseudo-classes#mapped-states) as shown in your documentation. This just feels awfully verbose and like a lot of extra fluff when all that is wanted in the first place is just to not actually do any namespacing at all. Using mapped states, instead of being able to just do:
```js
.root {
    -st-states: toggled, loading;
}
```

We now have to do:
```js
.root {
    -st-states: toggled("data-toggled"), loading("data-loading");
}
```

This is something that would need to be done for literally every single time that you use pseudo classes.

The end result is to try to be able to use something like this:
```js
export default ({toggled, loading, content}) => html`
<div class=${style.root}` data-loading=${loading} data-toggled=${toggled}>${content}</div>
`;
```
(with at least hyperHTML, attributes are automatically removed if their value is `null`)

In Closing
---

Just some food for thought as this tool develops, and perhaps thinking if it's worth the ability to at least chose to opt-out of namespacing pseudo-classes at the build step. I very well may be in the minority here where this is an issue, so definitely curious to hear other people's thoughts.

**Comment by Scott-MacD** [comment] 2018-05-09 01:50
Not quite the same, but related to https://github.com/wix/stylable/issues/313

**Comment by idoros** [comment] 2018-05-10 09:35
## State implementation details

I will try and breakdown our decision of how to represent states for component/element while answering the questions raised.

### State as attribute

> Is there any other big advantage to namespacing data-attributes?

The reason we choose to represent a state as an `attribute` and not a `CSS class` is because we wanted to target complex [non-boolean states](https://stylable.io/docs/references/state-parameter-types). 

Stylable already offers several build-in state types, like [enum](https://stylable.io/docs/references/state-parameter-types#enum) or [tag](https://stylable.io/docs/references/state-parameter-types#tag), and I would like to see Stylable offer other abilities like [multiple named parameters](https://github.com/wix/stylable/issues/269), [custom "nth" type](https://github.com/wix/stylable/issues/270) and [more...](https://stylable.io/docs/references/state-parameter-types#future-intent)

### State namespacing

Stylable aims at namespacing anything that might conflict, and states (attributes) are a big part of it.

> .root:toggled already namespaced due to .root being namespaced itself?

You are right that on the global level, the issue is small, as long as a state is always connected to a "typed" selector scope.

> there is the risk of :toggled being polluted by being passed directly from a parent component to a child component

I see this issue accures all the time, since components are composites of other components, and share DOM. 

The more obvious case is a component root element being another component, essentially sharing a DOM element.

And the other case is when a component "extends" one of its parts states. for example a Menu extending and adding a "selected" state to the internal Button definition:

```css
:import {
    -st-from: './button.st.css';
    -st-default: Button;
}
.button {
    -st-extends: Button;
    -st-states: selected;
}
```

You can see how [state inheritance](https://stylable.io/docs/references/pseudo-classes#state-inheritance) works in the docs.

### Mapped states 

[Mapped states](https://stylable.io/docs/references/pseudo-classes#mapped-states) are a way to by-pass the namespacing, however they are designed for something else, mapped states are used to target components that have predictable persistent DOM and are **not based on Stylable**.

## Solutions

**Opt-out of namespacing** although not using the build-in feature seems like miss to me. I can understand that there are cases where  the template engine has its limitations, but still choose this option only if your project only has simple templates and not components that might conflict.

**DOM utility**, just a simple function that accepts an `Element` together with props & prevProps and update the state. since "dynamic" attributes are not possible in `hyperHTML`. I think modifing the generated element is not a bad way to go. `lit-html`, by the way, has a [directive](https://github.com/Polymer/lit-html#directives) concept that can be used to apply such modifications:

```js
import style from './style.st.css';
const directive= createLitDriective(style);
html`<span stylable=${directive('root', {stateA:true})}></span>`;
```

**Comment by Scott-MacD** [comment] 2018-05-10 14:16
Thanks for the explanations @idoros, definitely all makes sense. I completely forgot about component extensions and the potential collisions there. We've become accustomed to working with the prototype chain in JS and structuring things in ways that we don't usually run into collisions (when we even do use extension to begin with), not to mention that IDEs are usually pretty good at flagging warnings about overridden properties. Working with states like this with inherited components in CSS is not a very well battle-tested concept for our team yet (as far as I'm aware, styleable is the first piece of tooling that makes this possible in a non-convoluted way?), so I can't say with confidence whether these similar concepts would be an issue in css or not, I appreciate the insight. I guess the bigger risk is on larger teams that may not be as intimate with every aspect of this part of the codebase, or perhaps extending component libraries.

As mentioned before, I don't think I've ever encountered issues with name collisions on a child/parent since we've started working in a component based architecture, but I can appreciate the fact that there are many different ways to do things and the real-world problems you guys are solving here.

**Comment by Scott-MacD** [comment] 2018-07-29 23:16
Just in case anyone else stumbles upon this who might also be trying to get stylable working with hyperHTML, a patch was made to hyperHTML to make this easier to do. See https://github.com/WebReflection/hyperHTML/issues/256 for the discussion.

**Comment by tomrav** [comment] 2018-07-30 09:48
@Scott-MacD many thanks for pushing this issue forward with HyperHTML, amazing to see this issue get resolved for a real world use-case.

If what you're working on is open, we'd love to take a look, and possibly reference it in our docs.

**Comment by Scott-MacD** [comment] 2018-07-30 13:18
Thanks @tomrav, the two projects we've been testing the waters with stylable with aren't open source, or even on the internet for that matter, but I am working on solidifying a tech stack to build isomorphic PWAs with hyperHTML and stylable and will make that repo open source, as well as a tutorial series on how and why (hence my recent activity in trying to find a way to clean up this interaction between the two libraries). I've got some more clean up to do before I get too far in, but more than happy to let the stylable team take a look when I have things ready.

I'm not sure how much traction I'll necessarily get, as this is my first time doing something like this and reaching out to the community, but I'll be promoting both of these technologies and would be completely open to a second set of eyes to ensure I'm promoting best practices with stylable, (same with @WebReflection and hyperHTML) when I get to that point.

Thanks for the help everyone.

**Comment by tomrav** [comment] 2018-07-31 09:29
I'm closing this issue as it appears to be resolved. Hurrah!

We'd be glad to invite you to join our Slack channel so we can chat a bit further about your project, and offer what help/pointers we can. If you're interested, please drop me an email at - tomr [at] wix.com

**Closed by tomrav** 2018-07-31 09:29 UTC
Labels: core, discussion, pseudo-state, question

**Comment by Scott-MacD** [comment] 2018-08-03 21:14
Thanks @tomrav, I've sent you an email.
